import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Link from "next/link";

import { AuthProvider } from "./_components/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NAV_LINKS = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Store", href: "/store" },
  {
    label: "Blog",
    href: "/blog",
    submenu: [{ label: "First post", href: "1" }],
  },
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex p-6">
          {NAV_LINKS.map((i, idx) => (
            <div key={idx} className="text-sm">
              <Link href={i.href} className="underline mx-3 text-white">
                {i.label}
              </Link>

              {i.submenu && i.submenu.length > 0 && (
                <ul className="list-disc ml-6 text-xs">
                  {i.submenu.map((subItem, subIdx) => (
                    <li key={subIdx}>
                      <Link
                        href={`${i.href}/${subItem.href}`}
                        className="underline flex text-white"
                      >
                        {subItem.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </nav>

        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
